trigger:
- master

stages:
- stage: ServerObjects
  jobs:
  - job: ServerObjects
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureKeyVault@1
      inputs:
        azureSubscription: 'MyAzureSubName(XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX)'
        KeyVaultName: 'MyAzureKeyVault'
        SecretsFilter: '*'
    - script: |
        echo $(admin-pem) | base64 -d > ~/.chef/admin.pem
        echo $(knife-rb) | base64 -d > ~/.chef/knife.rb
      displayName: 'Set up Knife'
    - script: echo "Data bags aren\'t complete JSON files so we can\'t lint them."
      displayName: 'Checking Data Bags'
    - script: |
        for f in environments/*.json
        do
          cat $f | jq -e
        done
      displayName: 'Checking Environments'
    - script: |
        for f in roles/*.json
        do
          cat $f | jq -e
        done
      displayName: 'Checking Roles'
    - script: |
        for f in data_bags/*/*.json
        do
          knife data bag from file $f
        done
      displayName: 'Upload Data Bags'
    - script: |
        for f in environments/*.json
        do
          knife environment from file $f
        done
      displayName: 'Upload Environments'
    - script: |
        for f in roles/*.json
        do
          knife role from file $f
        done
      displayName: 'Upload Roles'